In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("../Airbnb_NYC.csv")

In [4]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,20738991,Brownstone apartment in Bed-Stuy,37627534,Tim,Brooklyn,Bedford-Stuyvesant,40.68953,-73.93187,Private room,49,2,1,2017-09-11,0.05,1,0
1,10995810,Room in gorgeous Astoria Apartment,57055185,Halley,Queens,Astoria,40.76802,-73.91685,Private room,33,1,0,NaN,NaN,1,0
2,15195491,Private Room w/ Private Bath in Heart of Bed-Stuy,33612454,Lucey,Brooklyn,Bedford-Stuyvesant,40.68655,-73.94299,Private room,80,2,106,2019-06-24,3.14,1,47
3,7856476,"Private floor with private half-bath, living area",24629261,Natalie,Staten Island,Randall Manor,40.63878,-74.10636,private room,69,3,23,2019-06-07,0.52,1,172
4,19172876,"Private room with 2 queen sized beds, in Times SQ",133972085,"Yumi, Chizu",Manhattan,Midtown,40.75594,-73.98259,Private room,155,4,35,2019-06-23,1.45,3,157

In [5]:
pd.read_csv("../Airbnb_NYC.csv")

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,20738991,Brownstone apartment in Bed-Stuy,37627534,Tim,Brooklyn,Bedford-Stuyvesant,40.68953,-73.93187,Private room,49,2,1,2017-09-11,0.05,1,0
1,10995810,Room in gorgeous Astoria Apartment,57055185,Halley,Queens,Astoria,40.76802,-73.91685,Private room,33,1,0,NaN,NaN,1,0
2,15195491,Private Room w/ Private Bath in Heart of Bed-Stuy,33612454,Lucey,Brooklyn,Bedford-Stuyvesant,40.68655,-73.94299,Private room,80,2,106,2019-06-24,3.14,1,47
3,7856476,"Private floor with private half-bath, living area",24629261,Natalie,Staten Island,Randall Manor,40.63878,-74.10636,private room,69,3,23,2019-06-07,0.52,1,172
4,19172876,"Private room with 2 queen sized beds, in Times SQ",133972085,"Yumi, Chizu",Manhattan,Midtown,40.75594,-73.98259,Private room,155,4,35,2019-06-23,1.45,3,157
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42331,5404201,Sun-filled Brownstone in Brooklyn,28013319,Gagandeep,Brooklyn,Prospect Heights,40.67665,-73.97094,Entire home/apt,180,2,135,2019-06-16,2.62,1,151
42332,20860448,"ROOM EN NEW YORK, MANHATTAN",23005126,Juan,Queens,Holliswood,40.71768,-73.77308,Private room,125,3,0,NaN,NaN,1,363
42333,19382201,Your Quiet Refuge in the Heart of Manhattan,9405109,Carolina,Manhattan,Civic Center,40.71195,-74.00757,Entire home/apt,200,3,3,2019-04-15,0.13,1,19
42334,9777669,Charming 1 BD in Washington Heights,20068971,Jacqueline,Manhattan,Washington Heights,40.85147,-73.93771,Entire home/apt,125,2,0,NaN,NaN,1,0
42335,915020,Garden Apartment in Park Slope,181756,Roslyn,Brooklyn,South Slope,40.66414,-73.98457,Entire home/apt,150,3,136,2019-07-07,1.80,1,301

In [7]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,20738991,Brownstone apartment in Bed-Stuy,37627534,Tim,Brooklyn,Bedford-Stuyvesant,40.68953,-73.93187,Private room,49,2,1,2017-09-11,0.05,1,0
1,10995810,Room in gorgeous Astoria Apartment,57055185,Halley,Queens,Astoria,40.76802,-73.91685,Private room,33,1,0,NaN,NaN,1,0
2,15195491,Private Room w/ Private Bath in Heart of Bed-Stuy,33612454,Lucey,Brooklyn,Bedford-Stuyvesant,40.68655,-73.94299,Private room,80,2,106,2019-06-24,3.14,1,47
3,7856476,"Private floor with private half-bath, living area",24629261,Natalie,Staten Island,Randall Manor,40.63878,-74.10636,private room,69,3,23,2019-06-07,0.52,1,172
4,19172876,"Private room with 2 queen sized beds, in Times SQ",133972085,"Yumi, Chizu",Manhattan,Midtown,40.75594,-73.98259,Private room,155,4,35,2019-06-23,1.45,3,157

In [8]:
df.shape

(42336, 16)

In [9]:
df.columns.tolist()

['id',
 'name',
 'host_id',
 'host_name',
 'neighbourhood_group',
 'neighbourhood',
 'latitude',
 'longitude',
 'room_type',
 'price',
 'minimum_nights',
 'number_of_reviews',
 'last_review',
 'reviews_per_month',
 'calculated_host_listings_count',
 'availability_365']

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42336 entries, 0 to 42335
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              42336 non-null  int64
 1   name                            42140 non-null  object
 2   host_id                         42336 non-null  int64
 3   host_name                       42185 non-null  object
 4   neighbourhood_group             42336 non-null  object
 5   neighbourhood                   42336 non-null  object
 6   latitude                        42336 non-null  float64
 7   longitude                       42336 non-null  float64
 8   room_type                       42336 non-null  object
 9   price                           42336 non-null  object
 10  minimum_nights                  42264 non-null  object
 11  number_of_reviews               42336 non-null  int64
 12  last_review                     33476 non-null  object
 13  reviews_per_month               33451 non-null  object
 14  calculated_host_listings_count  42336 non-null  int64
 15  availability_365                42257 non-null  object
dtypes: float64(2), int64(4), object(10)
memory usage: 5.2+ MB

In [16]:
df["price"].head(20)

0       49
1       33
2       80
3       69
4      155
5     1000
6      295
7       50
8       65
9       60
10     280
11     150
12      65
13      60
14      80
15      87
16     230
17     110
18     220
19      50
Name: price, dtype: object

### Let's ask pandas: Which values in price cannot be converted to numbers?

In [19]:
price_numeric = pd.to_numeric(df["price"], errors="coerce")

In [20]:
df[price_numeric.isna()][["price"]].head(20)

                price
185              $575
279              $650
453            USD 63
543            USD 49
636            $96.00
642               $96
792     $ 750 / night
1259              $75
1535           USD 40
1621           $46.00
1942     $ 82 / night
1976     $ 78 / night
1985  $ 1,000 / night
2338              $95
2439           $48.00
2902           $99.00
3121           $46.00
3265    $ 182 / night
3364             $175
3412     $ 50 / night

In [21]:
df["price"] = pd.to_numeric(df["price"], errors="coerce")

### How many price values couldn't be directly converted to numbers?

In [30]:
price_numeric.isna().sum()

np.int64(208)

In [31]:
len(df)

42336

In [32]:
price_numeric.isna().sum() / len(df) * 100

np.float64(0.4913076341647771)

### Price value cleaning

In [33]:
df["price_clean"] = (
    df["price"]
    .astype(str)
    .str.replace(r"[^0-9.]", "", regex=True)
)

### creating a new column called price_clean

In [34]:
df.loc[
    price_numeric.isna(),
    ["price", "price_clean"]
].head(20)

      price price_clean
185     NaN
279     NaN
453     NaN
543     NaN
636     NaN
642     NaN
792     NaN
1259    NaN
1535    NaN
1621    NaN
1942    NaN
1976    NaN
1985    NaN
2338    NaN
2439    NaN
2902    NaN
3121    NaN
3265    NaN
3364    NaN
3412    NaN

In [35]:
df.loc[[185, 279, 453, 792, 1985], "price"]

185    NaN
279    NaN
453    NaN
792    NaN
1985   NaN
Name: price, dtype: float64

### aaahhh crap, the price variable got overwritten, let's try to fix it.

In [37]:
df = pd.read_csv("../Airbnb_NYC.csv")

In [38]:
df.loc[[185, 279, 453, 792, 1985], "price"]

185                $575
279                $650
453              USD 63
792       $ 750 / night
1985    $ 1,000 / night
Name: price, dtype: object

#### ok, we are back

In [39]:
df["price_clean"] = (
    df["price"]
    .astype(str)
    .str.replace(r"[^0-9.]", "", regex=True)
)

In [40]:
df.loc[[185, 279, 453, 792, 1985], ["price", "price_clean"]]

                price price_clean
185              $575         575
279              $650         650
453            USD 63          63
792     $ 750 / night         750
1985  $ 1,000 / night        1000

### NICE!

### Now, What data type are these two columns?

In [42]:
df[["price", "price_clean"]].dtypes

price          object
price_clean    object
dtype: object

#### convert the cleaned price to numeric

In [43]:
df["price_clean"] = pd.to_numeric(df["price_clean"], errors="coerce")

In [44]:
df[["price", "price_clean"]].dtypes

price           object
price_clean    float64
dtype: object

In [45]:
df["price_clean"].isna().sum()

np.int64(1)

In [47]:
df[df["price_clean"].isna()][["price", "price_clean"]]

         price  price_clean
31722  unknown          NaN

In [48]:
df["price_clean"].mean()

np.float64(153.75271052320775)

#### The price column contained inconsistent formats, including currency symbols

In [49]:
df["price_clean"].describe()

count    42335.000000
mean       153.752711
std        255.706952
min          0.000000
25%         69.000000
50%        107.000000
75%        175.000000
max      10128.000000
Name: price_clean, dtype: float64

####  $0 min and $10,12 max ?! This is weird. We got to look that up

#### Lets start by the "free" rooms

In [51]:
df[df["price_clean"] == 0][
    ["name", "neighbourhood_group", "room_type", "price", "price_clean"]
]

,name,neighbourhood_group,room_type,price,price_clean
2672,2 Bed 2 Bath Close to Park pool In Building,Manhattan,Entire home/apt,0,0.0
3760,Spacious Parkside Abode,Brooklyn,Private room,0,0.0
3796,Coliving in Brooklyn! Modern design / Shared room,Brooklyn,Shared room,0,0.0
9502,Cozy yet spacious private brownstone bedroom,Brooklyn,Private room,0,0.0
10969,the best you can find,Manhattan,Entire home/apt,0,0.0
28321,Contemporary bedroom in brownstone with nice view,Brooklyn,Private room,0,0.0
39104,"Sunny, Quiet Room in Greenpoint",Brooklyn,Private room,0,0.0
39691,"MARTIAL LOFT 3: REDEMPTION (upstairs, 2nd room)",Brooklyn,Private room,0,0.0
40852,"Huge Brooklyn Brownstone Living, Close to it all.",Brooklyn,Private room,0,0.0

#### now the priciest ones

In [52]:
df.nlargest(10, "price_clean")[
    ["name", "neighbourhood_group", "room_type", "price_clean"]
]

,name,neighbourhood_group,room_type,price_clean
12449,Spread out in Manhattan! :),Manhattan,Private room,10128.0
25479,Furnished room in Astoria apartment,Queens,Private room,10000.0
42223,Luxury 1 bedroom apt. -stunning Manhattan views,Brooklyn,Entire home/apt,10000.0
3190,"Quiet, Clean, Lit @ LES & Chinatown",Manhattan,Private room,9999.0
5509,2br - The Heart of NYC: Manhattans Lower East ...,Manhattan,Entire home/apt,9999.0
17234,Spanish Harlem Apt,Manhattan,Entire home/apt,9999.0
4588,Spacious Village 1 bedroom - 5 star rated host,Manhattan,Entire home/apt,8899.0
10103,Beautiful/Spacious 1 bed luxury flat-TriBeCa/Soho,Manhattan,Entire home/apt,8500.0
38587,Film Location,Brooklyn,Entire home/apt,8000.0
14933,East 72nd Townhouse by (Hidden by Airbnb),Manhattan,Entire home/apt,7703.0

In [53]:
df.nlargest(10, "price_clean")

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,price_clean
12449,14535633,Spread out in Manhattan! :),89905737,Eric,Manhattan,Washington Heights,40.84723,-73.94045,Private room,10128,14,1,2016-10-29,0.03,1,0,10128.0
25479,7003697,Furnished room in Astoria apartment,20582832,Kathrine,Queens,Astoria,40.76810,-73.91651,Private room,10000,100,2,"February 13, 2016",0.04,1,0,10000.0
42223,13894339,Luxury 1 bedroom apt. -stunning Manhattan views,5143901,Erin,Brooklyn,Greenpoint,40.73260,-73.95739,Entire home/apt,10000,5,5,2017-07-27,0.16,1,0,10000.0
3190,9528920,"Quiet, Clean, Lit @ LES & Chinatown",3906464,Amy,Manhattan,Lower East Side,40.71355,-73.98507,Private room,9999,99,6,2016-01-01,0.14,1,83,9999.0
5509,31340283,2br - The Heart of NYC: Manhattans Lower East ...,4382127,Matt,Manhattan,Lower East Side,40.71980,-73.98566,Entire home/apt,9999,30,0,NaN,NaN,1,365,9999.0
17234,4737930,Spanish Harlem Apt,1235070,Olson,Manhattan,East Harlem,40.79264,-73.93898,Entire home/apt,9999,5,1,2015-01-02,0.02,1,0,9999.0
4588,19263405,Spacious Village 1 bedroom - 5 star rated host,4279544,Abigail,Manhattan,Greenwich Village,40.72954,-74.00206,Entire home/apt,8899,4,6,2017-12-17,0.24,1,0,8899.0
10103,23377410,Beautiful/Spacious 1 bed luxury flat-TriBeCa/Soho,18128455,Rum,Manhattan,Tribeca,40.72197,-74.00633,Entire home/apt,8500,30,2,2018-09-18,0.18,1,251,8500.0
38587,2953058,Film Location,1177497,Jessica,Brooklyn,Clinton Hill,40.69137,-73.96723,Entire home/apt,8000,1,1,2016-09-15,0.03,11,365,8000.0
14933,22779726,East 72nd Townhouse by (Hidden by Airbnb),156158778,Sally,Manhattan,Upper East Side,40.76824,-73.95989,Entire home/apt,7703,1,0,NaN,NaN,12,146,7703.0

#### So, How many missing values does each column contain?

In [54]:
df.isna().sum().sort_values(ascending=False)

reviews_per_month                 8885
last_review                       8860
name                               196
host_name                          151
availability_365                    79
minimum_nights                      72
price_clean                          1
id                                   0
host_id                              0
room_type                            0
longitude                            0
latitude                             0
neighbourhood                        0
neighbourhood_group                  0
price                                0
number_of_reviews                    0
calculated_host_listings_count       0
dtype: int64

In [55]:
df.duplicated().sum()

np.int64(336)

In [56]:
df["id"].duplicated().sum()

np.int64(336)